#
# grade_button_interval_tooltips.py <generated by GitHub Copilot>
#

import math

from mnemosyne.libmnemosyne.plugin import Plugin
from mnemosyne.pyqt_ui.review_wdgt import ReviewWdgt


class IntervalTooltipReviewWdgt(ReviewWdgt):

    def set_grade_tooltip(self, grade, text):
        tooltip_text = text
        try:
            card = self.review_controller().card
            if card and self.review_controller().is_answer_showing():
                interval = self.scheduler().process_answer(card, grade, dry_run=True)
                days = int(math.ceil(interval / (24.0 * 60 * 60)))
                if days < 0:
                    days = 0
                day_text = "day" if days == 1 else "days"
                tooltip_text = f"{text}\nNext revision: in {days} {day_text}."
        except Exception:
            # Keep the default tooltip if the interval cannot be calculated.
            pass
        super().set_grade_tooltip(grade, tooltip_text)


class GradeButtonIntervalTooltipsPlugin(Plugin):

    name = "Grade button interval tooltips"
    description = "Show next revision delay in grade button tooltips (0-5)."
    gui_for_component = {
        "ScheduledForgottenNew": [
            ("grade_button_interval_tooltips", "IntervalTooltipReviewWdgt")
        ],
        "NewOnly": [
            ("grade_button_interval_tooltips", "IntervalTooltipReviewWdgt")
        ],
        "CramAll": [
            ("grade_button_interval_tooltips", "IntervalTooltipReviewWdgt")
        ],
        "CramRecent": [
            ("grade_button_interval_tooltips", "IntervalTooltipReviewWdgt")
        ],
    }
    supported_API_level = 3


# Register plugin.

from mnemosyne.libmnemosyne.plugin import register_user_plugin
register_user_plugin(GradeButtonIntervalTooltipsPlugin)