#
# grade_button_interval_tooltips.py <generated by GitHub Copilot>
#

import math

from mnemosyne.libmnemosyne.plugin import Plugin
from mnemosyne.pyqt_ui.review_wdgt import ReviewWdgt


DAY = 24 * 60 * 60
MONTH = 31
YEAR = 365


def format_revision_interval(interval_seconds):
    days = max(0, int(math.ceil(interval_seconds / DAY)))
    if days == 0:
        return "today"

    units = [
        ("year", YEAR),
        ("month", MONTH),
        ("day", 1),
    ]
    parts = []
    for name, size in units:
        count, days = divmod(days, size)
        if count:
            suffix = "" if count == 1 else "s"
            parts.append(f"{count} {name}{suffix}")
    return " ".join(parts)


def revision_interval_message(interval_seconds):
    formatted_interval = format_revision_interval(interval_seconds)
    if formatted_interval == "today":
        return "Next revision: today."
    return f"Next revision: in {formatted_interval}."


class IntervalTooltipReviewWdgt(ReviewWdgt):

    def set_grade_tooltip(self, grade, text):
        tooltip_text = text
        try:
            card = self.review_controller().card
            if card and self.review_controller().is_answer_showing():
                interval = self.scheduler().grade_answer(card, grade, dry_run=True)
                tooltip_text = f"{text}\n{revision_interval_message(interval)}"
        except Exception:
            # Keep the default tooltip if the interval cannot be calculated.
            pass
        super().set_grade_tooltip(grade, tooltip_text)

    def grade_answer(self, grade):
        card = self.review_controller().card
        super().grade_answer(grade)
        if card:
            interval = max(0, card.next_rep - self.scheduler().adjusted_now())
            print(revision_interval_message(interval))


class GradeButtonIntervalTooltipsPlugin(Plugin):

    name = "Grade button interval tooltips"
    description = "Show next revision delay in grade button tooltips (0-5)."
    gui_for_component = {
        "ScheduledForgottenNew": [
            ("grade_button_interval_tooltips", "IntervalTooltipReviewWdgt")
        ],
        "NewOnly": [
            ("grade_button_interval_tooltips", "IntervalTooltipReviewWdgt")
        ],
        "CramAll": [
            ("grade_button_interval_tooltips", "IntervalTooltipReviewWdgt")
        ],
        "CramRecent": [
            ("grade_button_interval_tooltips", "IntervalTooltipReviewWdgt")
        ],
    }
    supported_API_level = 3

    def activate(self):
        Plugin.activate(self)
        if self.database() and self.database().is_loaded():
            self.controller().reset_study_mode()

    def deactivate(self):
        deactivated = Plugin.deactivate(self)
        if deactivated and self.database() and self.database().is_loaded():
            self.controller().reset_study_mode()
        return deactivated


# Register plugin.

from mnemosyne.libmnemosyne.plugin import register_user_plugin
register_user_plugin(GradeButtonIntervalTooltipsPlugin)