# random_future_revision.py <generated by GitHub Copilot>
#
# Pulls one random card from the 20 cards with the furthest next
# repetition time and makes it due immediately when Mnemosyne starts.

import random
import time

from mnemosyne.libmnemosyne.hook import Hook
from mnemosyne.libmnemosyne.plugin import Plugin

number_of_cards_to_consider = 20
seconds_in_five_years = 5 * 365 * 24 * 60 * 60


class RandomFutureRevisionHook(Hook):

    used_for = "after_load"

    def run(self):
        print("[random_future_revision] after_load hook entered")
        db = self.database()
        if not db or not db.is_loaded():
            print("[random_future_revision] database not loaded")
            return

        threshold = int(time.time()) + seconds_in_five_years
        rows = db.con.execute(
            """select _id, next_rep, last_rep from cards
                where active=1 and grade>=2 and next_rep > ?
                order by next_rep desc
                limit ?""", (threshold, number_of_cards_to_consider)).fetchall()
        rows.sort(key=lambda row: row[2], reverse=True)

        if not rows:
            return

        card_id = random.choice([row[0] for row in rows])
        card = db.card(card_id, is_id_internal=True)
        if card.next_rep > 0:
            card.next_rep = 0
            db.update_card(card)


class RandomFutureRevisionPlugin(Plugin):

    name = "Random future revision on startup"
    description = (
        "On startup, choose a random card from cards whose next "
        "repetition is more than five years away and that have the "
        "lowest easiness, then make it due immediately."
    )
    components = [RandomFutureRevisionHook]
    supported_API_level = 3


# Register plugin.

from mnemosyne.libmnemosyne.plugin import register_user_plugin
plugin = register_user_plugin(RandomFutureRevisionPlugin)
plugin.activate()
