# random_future_revision.py <generated by GitHub Copilot>
#
# Pulls the card with the furthest last review timestamp and makes it due
# immediately when Mnemosyne starts.

import time

from mnemosyne.libmnemosyne.hook import Hook
from mnemosyne.libmnemosyne.plugin import Plugin

scheduled_threshold = 25
HOUR = 60 * 60


class RandomFutureRevisionHook(Hook):

    used_for = "after_load"

    def run(self):
        print("[random_future_revision] after_load hook entered")
        db = self.database()
        if not db or not db.is_loaded():
            print("[random_future_revision] database not loaded")
            return

        timestamp = int(time.time())
        try:
            day_starts_at = int(self.config()["day_starts_at"])
        except Exception:
            day_starts_at = 0
        timestamp -= day_starts_at * HOUR
        if time.localtime(timestamp).tm_isdst and time.daylight:
            timestamp -= time.altzone
        else:
            timestamp -= time.timezone
        adjusted_now = int(timestamp)

        scheduled_count = db.scheduled_count(adjusted_now)
        if scheduled_count >= scheduled_threshold:
            print(f"[random_future_revision] scheduled revision cards ({scheduled_count}) >= {scheduled_threshold}, skipping")
            return

        rows = db.con.execute(
            """select _id, next_rep, last_rep from cards
                where active=1 and grade>=2
                order by last_rep asc
                limit 1""" ).fetchall()

        if not rows:
            return

        card_id = rows[0][0]
        card = db.card(card_id, is_id_internal=True)
        if card.next_rep > 0:
            card.next_rep = 0
            db.update_card(card)


class RandomFutureRevisionPlugin(Plugin):

    name = "Random future revision on startup"
    description = (
        "On startup, choose the card with the oldest last review time "
        "and make it due immediately."
    )
    components = [RandomFutureRevisionHook]
    supported_API_level = 3


# Register plugin.

from mnemosyne.libmnemosyne.plugin import register_user_plugin
plugin = register_user_plugin(RandomFutureRevisionPlugin)
plugin.activate()
