# random_future_revision.py <generated by GitHub Copilot>
#
# Pulls the card with the furthest last review timestamp and makes it due
# immediately when Mnemosyne starts.

import time

from mnemosyne.libmnemosyne.hook import Hook
from mnemosyne.libmnemosyne.plugin import Plugin

x = 25


class RandomFutureRevisionHook(Hook):

    used_for = "after_load"

    def run(self):
        print("[random_future_revision] after_load hook entered")
        db = self.database()
        if not db or not db.is_loaded():
            print("[random_future_revision] database not loaded")
            return

        scheduled_count = db.con.execute(
            """select count(*) from cards
                where active=1 and grade>=2 and next_rep > 0""").fetchone()[0]
        if scheduled_count >= x:
            print(f"[random_future_revision] scheduled revision cards ({scheduled_count}) >= {x}, skipping")
            return

        rows = db.con.execute(
            """select _id, next_rep, last_rep from cards
                where active=1 and grade>=2
                order by last_rep asc
                limit 1""" ).fetchall()

        if not rows:
            return

        card_id = rows[0][0]
        card = db.card(card_id, is_id_internal=True)
        if card.next_rep > 0:
            card.next_rep = 0
            db.update_card(card)


class RandomFutureRevisionPlugin(Plugin):

    name = "Random future revision on startup"
    description = (
        "On startup, choose the card with the oldest last review time "
        "and make it due immediately."
    )
    components = [RandomFutureRevisionHook]
    supported_API_level = 3


# Register plugin.

from mnemosyne.libmnemosyne.plugin import register_user_plugin
plugin = register_user_plugin(RandomFutureRevisionPlugin)
plugin.activate()
